export const userData = [
  {
    id: "1a2b3c4d-001",
    name: "Aarav Patel",
    email: "aarav.patel@example.com",
    mobileno: "9876543210",
    dob: "1995-03-14",
    gender: true,
    address: "23 Nehru Nagar, Ahmedabad",
    city: "Ahmedabad",
    hobbies: ["Reading", "Traveling", "Music"],
    status: true,
  },
  {
    id: "1a2b3c4d-002",
    name: "Isha Sharma",
    email: "isha.sharma@example.com",
    mobileno: "9123456780",
    dob: "1998-07-22",
    gender: false,
    address: "45 Lajpat Nagar, Delhi",
    city: "Delhi",
    hobbies: ["Cooking", "Dancing", "Photography"],
    status: false,
  },
  {
    id: "1a2b3c4d-003",
    name: "Rohan Mehta",
    email: "rohan.mehta@example.com",
    mobileno: "9998887776",
    dob: "1992-11-30",
    gender: true,
    address: "12 Koregaon Park, Pune",
    city: "Pune",
    hobbies: ["Gaming", "Sports", "Music"],
    status: true,
  },
  {
    id: "1a2b3c4d-004",
    name: "Sneha Verma",
    email: "sneha.verma@example.com",
    mobileno: "9080706050",
    dob: "2000-05-09",
    gender: false,
    address: "17 Banjara Hills, Hyderabad",
    city: "Hyderabad",
    hobbies: ["Reading", "Yoga", "Cooking"],
    status: true,
  },
  {
    id: "1a2b3c4d-005",
    name: "Karan Gupta",
    email: "karan.gupta@example.com",
    mobileno: "9012345678",
    dob: "1997-01-18",
    gender: true,
    address: "5 MG Road, Mumbai",
    city: "Mumbai",
    hobbies: ["Photography", "Traveling", "Sports"],
    status: false,
  },
  {
    id: "1a2b3c4d-006",
    name: "Priya Nair",
    email: "priya.nair@example.com",
    mobileno: "9876001122",
    dob: "1996-09-10",
    gender: false,
    address: "11 Marine Drive, Mumbai",
    city: "Mumbai",
    hobbies: ["Music", "Yoga", "Cooking"],
    status: true,
  },
  {
    id: "1a2b3c4d-007",
    name: "Aditya Rao",
    email: "aditya.rao@example.com",
    mobileno: "9955443322",
    dob: "1993-04-25",
    gender: true,
    address: "9 Jubilee Hills, Hyderabad",
    city: "Hyderabad",
    hobbies: ["Sports", "Gaming", "Reading"],
    status: false,
  },
  {
    id: "1a2b3c4d-008",
    name: "Nisha Singh",
    email: "nisha.singh@example.com",
    mobileno: "9090909090",
    dob: "1999-08-19",
    gender: false,
    address: "55 Model Town, Delhi",
    city: "Delhi",
    hobbies: ["Dancing", "Music", "Cooking"],
    status: true,
  },
  {
    id: "1a2b3c4d-009",
    name: "Manav Joshi",
    email: "manav.joshi@example.com",
    mobileno: "9778899001",
    dob: "1994-06-12",
    gender: true,
    address: "14 Camp Area, Pune",
    city: "Pune",
    hobbies: ["Gaming", "Reading", "Sports"],
    status: true,
  },
  {
    id: "1a2b3c4d-010",
    name: "Tanya Deshmukh",
    email: "tanya.deshmukh@example.com",
    mobileno: "9876541000",
    dob: "2001-12-05",
    gender: false,
    address: "21 FC Road, Pune",
    city: "Pune",
    hobbies: ["Photography", "Yoga", "Traveling"],
    status: false,
  },
  {
    id: "1a2b3c4d-011",
    name: "Vikram Bhat",
    email: "vikram.bhat@example.com",
    mobileno: "9700012345",
    dob: "1989-02-14",
    gender: true,
    address: "4 Banjara Colony, Hyderabad",
    city: "Hyderabad",
    hobbies: ["Reading", "Gaming", "Traveling"],
    status: true,
  },
  {
    id: "1a2b3c4d-012",
    name: "Ritika Jain",
    email: "ritika.jain@example.com",
    mobileno: "9812345670",
    dob: "1997-10-28",
    gender: false,
    address: "18 Andheri East, Mumbai",
    city: "Mumbai",
    hobbies: ["Dancing", "Music", "Cooking"],
    status: false,
  },
  {
    id: "1a2b3c4d-013",
    name: "Harsh Tiwari",
    email: "harsh.tiwari@example.com",
    mobileno: "9332211456",
    dob: "1993-03-11",
    gender: true,
    address: "20 Nehru Place, Delhi",
    city: "Delhi",
    hobbies: ["Gaming", "Photography", "Sports"],
    status: true,
  },
  {
    id: "1a2b3c4d-014",
    name: "Kavya Pillai",
    email: "kavya.pillai@example.com",
    mobileno: "9098776655",
    dob: "1998-11-07",
    gender: false,
    address: "30 Churchgate, Mumbai",
    city: "Mumbai",
    hobbies: ["Yoga", "Traveling", "Reading"],
    status: true,
  },
  {
    id: "1a2b3c4d-015",
    name: "Rajat Kumar",
    email: "rajat.kumar@example.com",
    mobileno: "9876612345",
    dob: "1995-09-22",
    gender: true,
    address: "25 Ameerpet, Hyderabad",
    city: "Hyderabad",
    hobbies: ["Sports", "Gaming", "Music"],
    status: false,
  },
  {
    id: "1a2b3c4d-016",
    name: "Ananya Chatterjee",
    email: "ananya.chatterjee@example.com",
    mobileno: "9087654321",
    dob: "2000-02-16",
    gender: false,
    address: "65 Rajouri Garden, Delhi",
    city: "Delhi",
    hobbies: ["Reading", "Cooking", "Dancing"],
    status: true,
  },
  {
    id: "1a2b3c4d-017",
    name: "Dhruv Malhotra",
    email: "dhruv.malhotra@example.com",
    mobileno: "9345678901",
    dob: "1991-05-08",
    gender: true,
    address: "10 Baner Road, Pune",
    city: "Pune",
    hobbies: ["Sports", "Gaming", "Music"],
    status: true,
  },
  {
    id: "1a2b3c4d-018",
    name: "Meera Das",
    email: "meera.das@example.com",
    mobileno: "9234567890",
    dob: "1996-06-19",
    gender: false,
    address: "18 Bopal, Ahmedabad",
    city: "Ahmedabad",
    hobbies: ["Photography", "Reading", "Yoga"],
    status: false,
  },
  {
    id: "1a2b3c4d-019",
    name: "Siddharth Kapoor",
    email: "siddharth.kapoor@example.com",
    mobileno: "9321012345",
    dob: "1993-10-02",
    gender: true,
    address: "11 Viman Nagar, Pune",
    city: "Pune",
    hobbies: ["Gaming", "Sports", "Traveling"],
    status: true,
  },
  {
    id: "1a2b3c4d-020",
    name: "Rhea Sen",
    email: "rhea.sen@example.com",
    mobileno: "9223344556",
    dob: "2002-04-01",
    gender: false,
    address: "8 Nariman Point, Mumbai",
    city: "Mumbai",
    hobbies: ["Music", "Dancing", "Cooking"],
    status: false,
  },
  {
    id: "1a2b3c4d-021",
    name: "Arjun Khanna",
    email: "arjun.khanna@example.com",
    mobileno: "9123412345",
    dob: "1994-09-27",
    gender: true,
    address: "13 Sector 17, Delhi",
    city: "Delhi",
    hobbies: ["Reading", "Gaming", "Sports"],
    status: true,
  },
  {
    id: "1a2b3c4d-022",
    name: "Divya Iyer",
    email: "divya.iyer@example.com",
    mobileno: "9567890123",
    dob: "1999-12-17",
    gender: false,
    address: "44 Hitech City, Hyderabad",
    city: "Hyderabad",
    hobbies: ["Yoga", "Photography", "Music"],
    status: true,
  },
  {
    id: "1a2b3c4d-023",
    name: "Nikhil Reddy",
    email: "nikhil.reddy@example.com",
    mobileno: "9898765432",
    dob: "1995-06-26",
    gender: true,
    address: "28 Kukatpally, Hyderabad",
    city: "Hyderabad",
    hobbies: ["Gaming", "Traveling", "Sports"],
    status: false,
  },
  {
    id: "1a2b3c4d-024",
    name: "Pooja Mishra",
    email: "pooja.mishra@example.com",
    mobileno: "9334567890",
    dob: "1998-01-12",
    gender: false,
    address: "50 Dadar West, Mumbai",
    city: "Mumbai",
    hobbies: ["Reading", "Music", "Yoga"],
    status: true,
  },
  {
    id: "1a2b3c4d-025",
    name: "Ravi Bhatt",
    email: "ravi.bhatt@example.com",
    mobileno: "9412345678",
    dob: "1992-07-09",
    gender: true,
    address: "22 Navrangpura, Ahmedabad",
    city: "Ahmedabad",
    hobbies: ["Photography", "Gaming", "Sports"],
    status: true,
  },
  {
    id: "1a2b3c4d-026",
    name: "Simran Gill",
    email: "simran.gill@example.com",
    mobileno: "9098989898",
    dob: "2001-05-23",
    gender: false,
    address: "29 Connaught Place, Delhi",
    city: "Delhi",
    hobbies: ["Cooking", "Dancing", "Traveling"],
    status: false,
  },
  {
    id: "1a2b3c4d-027",
    name: "Tarun Bansal",
    email: "tarun.bansal@example.com",
    mobileno: "9312312312",
    dob: "1990-08-15",
    gender: true,
    address: "40 Satellite, Ahmedabad",
    city: "Ahmedabad",
    hobbies: ["Reading", "Gaming", "Music"],
    status: true,
  },
  {
    id: "1a2b3c4d-028",
    name: "Neha Kapoor",
    email: "neha.kapoor@example.com",
    mobileno: "9999912345",
    dob: "1997-02-09",
    gender: false,
    address: "6 Bandra West, Mumbai",
    city: "Mumbai",
    hobbies: ["Yoga", "Cooking", "Traveling"],
    status: true,
  },
  {
    id: "1a2b3c4d-029",
    name: "Aman Yadav",
    email: "aman.yadav@example.com",
    mobileno: "9555567890",
    dob: "1994-10-21",
    gender: true,
    address: "32 Begumpet, Hyderabad",
    city: "Hyderabad",
    hobbies: ["Sports", "Reading", "Music"],
    status: false,
  },
  {
    id: "1a2b3c4d-030",
    name: "Sara Fernandes",
    email: "sara.fernandes@example.com",
    mobileno: "9877012345",
    dob: "2000-06-03",
    gender: false,
    address: "14 Koregaon Park, Pune",
    city: "Pune",
    hobbies: ["Photography", "Yoga", "Cooking"],
    status: true,
  },
];
